  journalist_task: 
    description: >
      Conduct research on financial news related to {company_ticker}, include:\n
      1. Retrive the 5-10 most recent news articles on 2025 about {company_ticker}\n
      2. For each article, extract the title, publisher, date\n
      3. Summarize the core topic or event covered by each articles.\n
      4. Perform sentiment analysis: label each article as Positive, Negative, or neutral\n
      5. Ensure findings useful for invesment decision-making.\n
      Use reputable financial websites for data.
    expected_output: >
      A detailed 200-word research report with data sources and brief analysis.

  macro_task:
    description: >
      Conduct research on macroeconomic indicators related to {company_ticker}'s country, include:\n
      1. Review last 5 years of macroecnomic data.\n
      2. Identify and analyze key macroeconomic indicators (e.g., GDP growth, inflation, interest rates).\n
      2. Summarize the current economic conditions and trends.\n
      3. Explain how these trends may influence {company_ticker}'s stock price.\n
      4. Provide insights on future stock price trends based on the expected trajectory of these macroeconomic factors.\n
      Use for MacroEconomicDataTool tool for data retrieving.
    expected_output: >
      A detailed 200-word research report with data sources and brief analysis. 

  fundamental_task:
    description: >
      Conduct research on {company_ticker}'s financials, include:\n
      1. Review the last 3 years of financial statements (revenue, earnings, net income).\n
      2. Key ratios (P/E, P/B, P/S, PEG, Debt-to-Equity, ROE, etc.).\n"
      3. Revenue and earnings growth trends.\n
      4. Management effectiveness (ROE, capital allocation).\n
      5. Growth catalysts and risks (2-3 years).\n
      6. DCF valuation model with assumptions.\n
      Use 'FundamentalAnalysisTool' to gather data and perform analysis.
    expected_output: >
      A detailed 200-word research report with data sources and brief analysis.

  reporter_task:
    description: >
      Create a concise investment report for {company_ticker}. The report should include:\n
      1. Executive Summary: Investment recommendation (Buy/Sell) based on findings.\n
      2. Company Snapshot: Brief overview of the company's operations and market position.\n
      3. Financial Highlights: Key financial metrics (e.g., revenue, net income, P/E ratio) and peer comparison.\n
      4. Fundamental Analysis: Summary of growth trends, ratios, and DCF valuation.\n
      5. Risk and Opportunity: Major risks and growth catalysts.\n
      6. Sentiment Analysis: Sentiment analysis from news articles.\n
      7. Macroecnomic Condition: Macroecnomic analysis based on it's indicator trends.\n
      8  Price Target: forecast 12-month market condition.\n
      9. Rationale for Investment: Potential upsides and downsides of investing in the company.\n
      Use the results from agents to generate the report
    expected_output: >
      A 600-word investment report with clear sections, key insights.

